#!/usr/bin/env bash
#Display numbers from 1 to 20 and use case 
#for the different iterations

i=1
while [ $i -le 20 ]
do
	echo "$i"
	i=$(( i +1 ))

	case $i in
		4) echo "bad luck for China";;
		9) echo "bad luck for Japan";;
		17) echo "good luck for Italy";;
		*) ;;	
	esac

done
