#!/usr/bin/env bash
#Process and PID file
dir(){
    rm /var/run/myscript.pid 
exit
}

trap "echo I hate the kill command;dir" SIGTERM
trap "echo Y U no love me?!;dir" SIGINT

echo $$ >> /var/run/myscript.pid
while '[ true ]'; do
	echo " To infinity and beyond"
done
